version: '3'
services:
    web-client:
        build:
            dockerfile: Dockerfile
            context: ./standfire-web-client
        ports:
          - '8080:8080'
    backend:
        restart: always
        build:
          dockerfile: Dockerfile
          context: ./standfire-backend
        ports:
          - '5000:5000'